spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.234.121.26:3306/nd_telemedicine_app?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: TencentCloud7
  mail:
    host: smtp.163.com
    username: sifangao97@163.com
    password: GURRVYMTIDJUVWHM
    port: 25

  mybatis:
    mapper-locations: mappers/*Mapper.xml

server:
  port:8080
